config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, skip: :all
    devise_scope :end_user do
      get 'end_users/sign_in' => 'end_users/end_users/sessions#new', as: 'new_end_user_session'
      post 'end_users/sign_in' => 'end_users/end_users/sessions#create', as: 'end_user_session'
      delete 'end_users/sign_out' => 'end_users/end_users/sessions#destroy', as: 'destroy_end_user_session'
      get 'end_users/sign_up' => 'end_users/end_users/registrations#new', as: 'new_end_user_registration'
      post 'end_users' => 'end_users/end_users/registrations#create', as: 'end_user_registration'
      get 'end_users/password/new' => 'end_users/end_users/passwords#new', as: 'new_end_user_password'
  end

      root 'items#top'
      get "/about" => "abouts#about"
      resources :items, only: [:index, :show]
      patch 'end_users/withdraw' => 'end_users#withdraw'
      resources :end_users, only: [:edit, :update]
      get 'end_users/my_page' => 'end_users#show'
      get 'end_users/unsubscribe' => 'end_users#unsubscribe'

      resources :cart_items, only: [:index, :update, :destroy, :create ] do
        collection do
          delete 'destroy_all'
        end
      end

      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      get 'orders/complete' => 'orders#complete' ,as: 'order_complete'
      resources :orders, only: [:new, :create, :index, :show ]
      post 'orders/confirm:id' => 'orders#confirm' ,as: 'order_comfirm'

      resources :addresses, only: [:index, :edit, :create, :update, :destroy ]

      get 'admins' => 'admins#top'

  namespace :admins do
      resources :items, only: [:index, :new, :create, :show, :edit, :update ]
      resources :genres, only: [:index, :create, :edit, :update ]
      resources :end_users, only: [:index, :show, :edit, :update ]
      patch 'admins/end_users/:id/unsubscribe' => 'admins/end_users#unsubscribe'
      resources :orders, only: [:index, :show, :update ]
      resources :order_details, only: [:update]
  end


  devise_for :admins, skip: :all
    devise_scope :admin do
      get 'admins/sign_in' => 'admins/admins/sessions#new', as: 'new_admin_session'
      post 'admins/sign_in' => 'admins/admins/sessions#create', as: 'admin_session'
      delete 'admins/sign_out' => 'admins/admins/sessions#destroy', as: 'destroy_admin_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :end_user
	validates :amount, presence: true
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	# before_action :authenticate_end_user!
	def index
		@cart_items = CartItem.where(end_user_id: current_end_user.id)
	end

	def update
		@cart_item = CartItem.find(params[:id])
		if @cart_item.update(amount: params[:amount])
          redirect_to cart_items_path(@cart_item)
        end
	end

	def destroy
		@cart_item = CartItem.find(params[:id])
    	@cart_item.destroy
    	redirect_to cart_items_path
	end

	def destroy_all
		CartItem.destroy_all
		redirect_to cart_items_path
	end

	def create
		@cart_items = CartItem.all
		@end_user_item = current_end_user.cart_items.find_by(item_id: params[:item_id])
		@end_user_item
		if @end_user_item.present?
			@end_user_item.amount += params[:amount].to_i
		else
			@end_user_item = current_end_user.cart_items.new(cart_item_params)
			@end_user_item.item_id = params[:item_id]
    	end
    	@end_user_item.save!
    	redirect_to cart_items_path
	end

private
	def cart_item_params
		 params.permit(:amount, :item_id, :end_user_id)
    end

	def setup_cart_item!
    	@cart_item = end_user.cart_items.find_by(item_id: params[:item_id])
  	end
end

app/helpers/end_users/cart_items_helper.rb
module EndUsers::CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="body">
<h3>ショッピングカート</h3>
<%= link_to "カートを空にする", cart_items_destroy_all_path(@cart_items), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger pull-right" %>


<table class="table table-bordered">
			<thead>
				<tr>
					<th>商品名</th>
					<th>単価（税込）</th>
					<th>数量</th>
					<th>小計</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @total_price = 0 %>
				<% @cart_items.each do |cart_item| %>
				<tr>
					<td>
						<%= attachment_image_tag @cart_item, :item_id, :fill, 50, 100 %>
						<%= cart_item.item.name %>
					</td>

					<td>
						<%= cart_item.item.price %>
					</td>

					<td>
						<%= form_with(model: cart_item, local: true, url: cart_item_path(cart_item), method: :patch) do |f| %>
						<%= number_field_tag :amount, cart_item.amount %>
						<%= f.submit '変更', class: "btn btn-primary" %>
						<% end %>
					</td>

					<td>
						<%= cart_item.item.price * cart_item.amount.to_i %>
					</td>

					<td>
						<%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn-sm btn-danger" %>
					</td>
				</tr>
				<% @total_price += cart_item.item.price  * cart_item.amount %>
				<% end %>
			</tbody>
</table>

<%= link_to "買い物を続ける", items_path, class: "btn btn-primary" %>
<table class="table table-bordered">
<th>合計金額</th>
<td><%= @total_price.to_i %></td>
</table>
<%= form_with(model: @order, local: true, url: new_order_path, method: :get) do |f| %>
<%= f.submit "情報入力に進む", class: "btn btn-success pull-center" %>
<% end %>

</div>