config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, skip: :all
    devise_scope :end_user do
      get 'end_users/sign_in' => 'end_users/end_users/sessions#new', as: 'new_end_user_session'
      post 'end_users/sign_in' => 'end_users/end_users/sessions#create', as: 'end_user_session'
      delete 'end_users/sign_out' => 'end_users/end_users/sessions#destroy', as: 'destroy_end_user_session'
      get 'end_users/sign_up' => 'end_users/end_users/registrations#new', as: 'new_end_user_registration'
      post 'end_users' => 'end_users/end_users/registrations#create', as: 'end_user_registration'
      get 'end_users/password/new' => 'end_users/end_users/passwords#new', as: 'new_end_user_password'
  end

      root 'items#top'
      get "/about" => "abouts#about"
      resources :items, only: [:index, :show]
      patch 'end_users/withdraw' => 'end_users#withdraw'
      resources :end_users, only: [:edit, :update]
      get 'end_users/my_page' => 'end_users#show'
      get 'end_users/unsubscribe' => 'end_users#unsubscribe'

      resources :cart_items, only: [:index, :update, :destroy, :create ] do
        collection do
          delete 'destroy_all'
        end
      end

      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      get 'orders/complete' => 'orders#complete' ,as: 'order_complete'
      resources :orders, only: [:new, :create, :index, :show ]
      post 'orders/confirm:id' => 'orders#confirm' ,as: 'order_comfirm'

      resources :addresses, only: [:index, :edit, :create, :update, :destroy ]

      get 'admins' => 'admins#top'

  namespace :admins do
      resources :items, only: [:index, :new, :create, :show, :edit, :update ]
      resources :genres, only: [:index, :create, :edit, :update ]
      resources :end_users, only: [:index, :show, :edit, :update ]
      patch 'admins/end_users/:id/unsubscribe' => 'admins/end_users#unsubscribe'
      resources :orders, only: [:index, :show, :update ]
      resources :order_details, only: [:update]
  end


  devise_for :admins, skip: :all
    devise_scope :admin do
      get 'admins/sign_in' => 'admins/admins/sessions#new', as: 'new_admin_session'
      post 'admins/sign_in' => 'admins/admins/sessions#create', as: 'admin_session'
      delete 'admins/sign_out' => 'admins/admins/sessions#destroy', as: 'destroy_admin_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :cart_ietmes, dependent: :destroy
	belongs_to :genre
	attachment :image
	has_many :order_details, dependent: :destroy

	validates :genre_id, presence: true
	validates :name, presence: true
	validates :introduction, presence: true
	validates :price, presence: true

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	before_action :authenticate_admin!
	def index
		@items = Item.all
		@item = Item.new
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to admins_item_path(@item)
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to admins_item_path(@item)
    end

	private
	def item_params
		params.require(:item).permit(:name, :introduction, :price, :image, :genre_id, :is_active)
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def top
		@items = Item.all
	end

	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

private
	def item_params
    	params.require(:item).permit(:name, :introduce, :image, :price, :is_active)
	end

end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/end_users/items_helper.rb
module EndUsers::ItemsHelper
end

app/views/items/index.html.erb
<div class="body">
	<div class="container">
		<div class="row">

			<div class="col-ls-3">
  				<div class="border">
					<h4 class="genres_title"><strong>ジャンル検索</strong></h4>
						<nav>
							<ul>
								<div class="genres_list">
									<li class="genres_list_item"><%= link_to 'ケーキ', items_path %></li>
									<li class="genres_list_item"><%= link_to '焼き菓子', items_path %></li>
									<li class="genres_list_item"><%= link_to 'プリン', items_path %></li>
									<li class="genres_list_item"><%= link_to 'キャンディー', items_path %></li>
								</div>
							</ul>
						</nav>
				</div>
			</div>

				<div class="col-ls-9">
				<h2><strong class="item_index">商品一覧</strong></h2>
					<% @items.each do |item| %>
						<div class="recommend_item">
							<%= link_to item_path(item) do %>
								<%= attachment_image_tag(item, :image, :fill, 100, 100) %>
							<% end %>

							<strong>
								<li class="item_name"><%= item.name %></li>
							</strong>
							<strong class="price">￥<%= item.price %></strong>
						</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/items/show.html.erb
<div class="body">
	<div class="container">
		<div class="row">

  			<div class="col-ls-3">
  				<div class="border">
					<h4 class="genres_title"><strong>ジャンル検索</strong></h4>

						<nav>
							<ul>
								<div class="genres_list">
									<li class="genres_list_item"><%= link_to 'ケーキ', item_path %></li>
									<li class="genres_list_item"><%= link_to '焼き菓子', item_path %></li>
									<li class="genres_list_item"><%= link_to 'プリン', item_path %></li>
									<li class="genres_list_item"><%= link_to 'キャンディー', item_path %></li>
								</div>
							</ul>
						</nav>
					</div>
				</div>

				<div class="col-ls-9">
					<div class="main_show">
						<%= form_with(model: @cart_item, local: true, url: cart_items_path) do |f| %>

							<%= f.hidden_field :item_id, :value => @item.id %>

								<%= attachment_image_tag @item, :image, :fill, 400, 400 %>

									<h3><strong><%= @item.name %></strong></h3>

									<div class="item_text"><%= @item.introduction %></div>

									<strong class="item_price">￥<%= @item.price %></strong>（税込）

									<div class="scroll">
        								<%= f.select :amount, [["１", 1], ["２", 2],["3",3],["4",4],["5",5]], include_blank: "個数選択" %>
										<%= f.submit 'カートに入れる', class: "btn btn-primary"%>
									</div>
						    <% end %>
					</div>
				</div>
		</div>
	</div>
</div>

app/views/items/top.html.erb
<div class="body">
	<div class="container">
  		<div class="row">

  			<div class="col-ls-3">
				<div class="border">
					<h4 class="genres_title"><strong>ジャンル検索</strong></h4>
						<nav>
							<ul>
								<div class="genres_list">
									<li class="genres_list_item"><%= link_to 'ケーキ', items_path %></li>
									<li class="genres_list_item"><%= link_to '焼き菓子', items_path %></li>
									<li class="genres_list_item"><%= link_to 'プリン', items_path %></li>
									<li class="genres_list_item"><%= link_to 'キャンディー', items_path %></li>
								</div>
							</ul>
						</nav>
				</div>
			</div>

			<div class="col-ls-9">
				<div class="main">
					<div class="text-all">
						<div class="top-text">
							<span class="text"><p>ようこそ、NaganoCakeへ！<br>
								このサイトは、ケーキ販売のECサイトになります。<br>
								会員ではない方も商品の閲覧はできますが、<br>
								購入には会員登録が必要になります。</p>
							</span>
						</div>
					</div>

					<div class="clearfix">
						<h2><strong>オススメ商品</strong></h2>
							<% @items.each do |item| %>
								<div class="recommend_item">
									<%= attachment_image_tag(@item, :image, :fill, 50, 50) %>
										<strong>
											<li class="item_name">商品名<%= item.name %></li>
										</strong>
										<strong>￥<%= item.price %></strong>
								</div>
							<% end %>
					</div>

					<div class="text-right">
						<%= link_to "もっと見る", items_path(@items) %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>