config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, skip: :all
    devise_scope :end_user do
      get 'end_users/sign_in' => 'end_users/end_users/sessions#new', as: 'new_end_user_session'
      post 'end_users/sign_in' => 'end_users/end_users/sessions#create', as: 'end_user_session'
      delete 'end_users/sign_out' => 'end_users/end_users/sessions#destroy', as: 'destroy_end_user_session'
      get 'end_users/sign_up' => 'end_users/end_users/registrations#new', as: 'new_end_user_registration'
      post 'end_users' => 'end_users/end_users/registrations#create', as: 'end_user_registration'
      get 'end_users/password/new' => 'end_users/end_users/passwords#new', as: 'new_end_user_password'
  end

      root 'items#top'
      get "/about" => "abouts#about"
      resources :items, only: [:index, :show]
      patch 'end_users/withdraw' => 'end_users#withdraw'
      resources :end_users, only: [:edit, :update]
      get 'end_users/my_page' => 'end_users#show'
      get 'end_users/unsubscribe' => 'end_users#unsubscribe'

      resources :cart_items, only: [:index, :update, :destroy, :create ] do
        collection do
          delete 'destroy_all'
        end
      end

      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      get 'orders/complete' => 'orders#complete' ,as: 'order_complete'
      resources :orders, only: [:new, :create, :index, :show ]
      post 'orders/confirm:id' => 'orders#confirm' ,as: 'order_comfirm'

      resources :addresses, only: [:index, :edit, :create, :update, :destroy ]

      get 'admins' => 'admins#top'

  namespace :admins do
      resources :items, only: [:index, :new, :create, :show, :edit, :update ]
      resources :genres, only: [:index, :create, :edit, :update ]
      resources :end_users, only: [:index, :show, :edit, :update ]
      patch 'admins/end_users/:id/unsubscribe' => 'admins/end_users#unsubscribe'
      resources :orders, only: [:index, :show, :update ]
      resources :order_details, only: [:update]
  end


  devise_for :admins, skip: :all
    devise_scope :admin do
      get 'admins/sign_in' => 'admins/admins/sessions#new', as: 'new_admin_session'
      post 'admins/sign_in' => 'admins/admins/sessions#create', as: 'admin_session'
      delete 'admins/sign_out' => 'admins/admins/sessions#destroy', as: 'destroy_admin_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  # validates :last_name, presence: true
  # validates :first_name, presence: true
  # validates :last_name_kana, presence: true
  # validates :first_name_kana, presence: true
  # validates :email, presence: true
  # validates :encrypted_password, presence: true
  # validates :postal_code, presence: true
  # validates :address, presence: true
  # validates :telephone_number, presence: true

 def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
	before_action :authenticate_admin!
	def index
		@end_users = EndUser.all
	end

	def show
		@end_user = EndUser.find(params[:id])
	end

	def edit
		@end_user = EndUser.find(params[:id])
	end

	def update
		@end_user = EndUser.find(params[:id])
		@end_user.update(end_user_params)
		redirect_to admins_end_user_path(@end_user.id)
	end

	private
    def end_user_params
      params.require(:end_user).permit(
      	:last_name,
      	:first_name,
      	:last_name_kana,
      	:first_name_kana,
      	:email,
      	:postal_code,
      	:address,
      	:telephone_number,
      	:is_deleted
      	)
    end
end

app/controllers/end_users/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
	def show
		@end_user = current_end_user
	end

	def edit
		@end_user = EndUser.find(params[:id])
		@end_user = current_end_user
	end

	def update
		@end_user = current_end_user
		@end_user = EndUser.find(params[:id])
		@end_user.update(end_user_params)
		redirect_to end_users_my_page_path
		if current_end_user != @end_user
           redirect_to end_users_my_page_path(current_end_user)
        end
	end
	# unsubscribe退会処理画面を表示する
	def unsubscribe
		@end_user = current_end_user
	end
	# withdraw退会処理を実行する、:rootはroot_pathに変更
	def withdraw
		@end_user = current_end_user
    	@end_user.update(is_deleted: true)
    	reset_session
    	redirect_to root_path
	end

	private
    def end_user_params
    params.require(:end_user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/end_users/addresses_helper.rb
module EndUsers::AddressesHelper
end

app/helpers/end_users/cart_items_helper.rb
module EndUsers::CartItemsHelper
end

app/helpers/end_users/items_helper.rb
module EndUsers::ItemsHelper
end

app/helpers/end_users/orders_helper.rb
module EndUsers::OrdersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/edit.html.erb
<div class="container">
     <div class="row">
		<div class="body">

		<h1>登録情報編集</h1>
			<%= form_with(model: @end_user, local: true) do |f| %>
		<h3>名前</h3>
			(姓)<%= f.text_field :last_name %>
			(名)<%= f.text_field :first_name %>
		<h3>フリガナ</h3>
			(セイ)<%= f.text_field :last_name_kana %>
			(メイ)<%= f.text_field :first_name_kana %>
		<h3>メールアドレス</h3>
			<%= f.text_field :email %>
		<h3>郵便番号(ハイフンなし)</h3>
			<%= f.text_field :postal_code %>
		<h3>住所</h3>
			<%= f.text_area :address %>
		<h3>電話番号(ハイフンなし)</h3>
			<%= f.text_field :telephone_number %>
			<%= f.submit '編集内容を保存する' %>
			<%= link_to "退会する",end_users_unsubscribe_path, class: "btn btn-danger" %>
		<% end %>
	<!-- 項目、記入欄を横並びにしたい -->
		</div>
	</div>
</div>

app/views/end_users/show.html.erb
<div class="container">
     <div class="row">
		<div class="body">
			<div class="table-title">
				<h1>マイページ</h1>
			</div>


			<div class=“table”>
				<span style="font-size: 20px">登録情報</span>
				<span><%= link_to "編集する", edit_end_user_path(@end_user.id), class: "btn btn-success" %></span>
				<span><%= link_to "パスワードを変更する", new_end_user_password_path(current_end_user), class: "btn btn-success" %></span>
			</div>

			<table class = "table">
				<tr>
					<td>氏名</td>
					<td><%= @end_user.last_name %><%= @end_user.first_name %></td>
				</tr>
				<tr>
					<td>カナ</td>
					<td><%= @end_user.last_name_kana %><%= @end_user.first_name_kana %></td>
				</tr>
				<tr>
					<td>郵便番号</td>
					<td><%= @end_user.postal_code %></td>
				</tr>
				<tr>
					<td>住所</td>
					<td><%= @end_user.address %></td>
				</tr>
				<tr>
					<td>メールアドレス</td>
					<td><%= @end_user.email %></td>
				</tr>
				<tr>
					<td>電話番号</td>
					<td><%= @end_user.telephone_number %></td>
				</tr>
			</table>

			<table class = "table">
				<tr>
					<td>配送先</td>
					<td><%= link_to "一覧を見る",addresses_path(@end_user.id), class: "btn btn-success" %></td>
		    		</tr>
			    <tr>
					<td>注文履歴</td>
					<td><%= link_to "一覧を見る",orders_path, class: "btn btn-success" %></td>
	    		</tr>
			</table>
		</div>
	</div>
</div>





<!-- マイページ
<body>
<div class=“table-title”>
<h3>マイページ</h3>
</div>
<div class=“table”>
	<span style=“font-size: 20px”>登録情報</span>
	<span><%#= link_to “編集する“, edit_end_user_path(@end_user.id), class: “btn btn-success” %></span>
	<span><%#= link_to “パスワードを変更する“, edit_end_user_password_path(current_end_user), class: “btn btn-success” %></span>
</div>
<table class = “table”>
			<tr>
				<td>氏名</td>
				<td><%= @end_user.last_name %><%= @end_user.first_name %></td>
			</tr>
			<tr>
				<td>カナ</td>
				<td><%= @end_user.last_name_kana %><%= @end_user.first_name_kana %></td>
			</tr>
			<tr>
				<td>郵便番号</td>
				<td><%= @end_user.postal_code %></td>
			</tr>
			<tr>
				<td>住所</td>
				<td><%= @end_user.address %></td>
			</tr>
			<tr>
				<td>メールアドレス</td>
				<td><%= @end_user.email %></td>
			</tr>
			<tr>
				<td>電話番号</td>
				<td><%= @end_user.telephone_number %></td>
			</tr>
</table>
<table class = “table”>
			<tr>
			<td>配送先</td>
			<td><%#= link_to “一覧を見る“,addresses_path(@end_user.id), class: “btn btn-success” %></td>
		    </tr>
		    <tr>
			<td>注文履歴</td>
			<td><%#= link_to “一覧を見る“,orders_path(@end_user.id), class: “btn btn-success” %></td>
		    </tr>
</table>
</body> -->

app/views/end_users/unsubscribe.html.erb
<div class="container">
     <div class="row">
		<div class="body">
			<h2>本当に退会しますか？</h2>
				<p>退会すると、会員登録情報や<br>これまでの購入履歴が閲覧できなくなります。<br>
					退会する場合は、「退会する」をクリックしてください。</p>

				<%= link_to "退会しない", end_users_my_page_path(@end_user.id), class: "btn btn-success" %>
				<%= link_to "退会する",end_users_withdraw_path, method: :patch, class: "btn btn-danger", data:{confirm: "Are you sure？"} %>
		</div>
	</div>
</div>
<!-- 退会しないボタンのパス名、ボタンの横ならび、退会するボタンのバリデーションかけるか -->

<!-- https://qiita.com/facultyoflaw11/items/664c5c0fa0cd09bece38 -->